apiVersion: v1
kind: ConfigMap
metadata:
  name: skirmshop-drive-s3-config
  labels:
    app.kubernetes.io/name: skirmshop-drive-mirror
    app.kubernetes.io/component: s3-config
data:
  S3_BUCKET: "skirmshop-drive"
  S3_REGION: "us-east-1"
  S3_ENDPOINT: "http://skirmshop-drive-s3.backup-hub.svc.cluster.local:9000"
