apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: skirmbooks-backup-s3-read-v2
  labels:
    app.kubernetes.io/name: skirmshop-drive-mirror
    app.kubernetes.io/component: synapse-backup-read-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: skirmbooks-backup-s3-read-v2
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: skirmshop-drive-mirror
          app.kubernetes.io/component: synapse-backup-read-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/skirmshop-drive/synapse-backup-read-v2
        property: AWS_ACCESS_KEY_ID
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/skirmshop-drive/synapse-backup-read-v2
        property: AWS_SECRET_ACCESS_KEY
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
